package dukes.greeting;

// Make Greeting a Jakarta Persistence Entity that is not Cacheable
import jakarta.persistence.Cacheable;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import java.io.Serializable;
import java.util.Objects;
import java.util.UUID;

/**
 * Greating class that contains a gretting message
 *
 * @author Sxtormulo
 */
@Cacheable(false)
public class Greeting implements Serializable
{

    // Add a field called id as primary key. Use autogenerated UUIDs for the primary key
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    // Add a field called message. Use String as type for the field
    private String message;

    /**
     * Construct a new greeting
     *
     * @param message the message of the greeting
     */
    public Greeting(String message)
    {
        this.message = message;
    }

    @Override
    public boolean equals(Object obj)
    {
        if(this == obj) return true;
        if(obj == null) return false;
        if(getClass() != obj.getClass()) return false;
        final Greeting other = (Greeting) obj;
        if(!Objects.equals(this.message, other.message)) return false;
        return Objects.equals(this.id, other.id);
    }

    /**
     * Get the id of the current instance
     *
     * @return the current id
     */
    public UUID getId()
    {
        return id;
    }

    /**
     * Set a new id for the instance
     *
     * @param id the new id
     */
    public void setId(UUID id)
    {
        this.id = id;
    }

    // Getters and Setters
    /**
     * Get the message of the current instance
     *
     * @return the current message
     */
    public String getMessage()
    {
        return message;
    }

    /**
     * Set a new message for the current instance
     *
     * @param message the new message
     */
    public void setMessage(String message)
    {
        this.message = message;
    }

    @Override
    public int hashCode()
    {
        int hash = 7;
        hash = 37 * hash + Objects.hashCode(this.id);
        hash = 37 * hash + Objects.hashCode(this.message);
        return hash;
    }

    @Override
    public String toString()
    {
        return "Greeting{" + "id=" + id + ", message=" + message + '}';
    }

}
